= Demo for MicroProfile Config

== Demo Application

The application contains simple demos for MicroProfile components in dedicated packages.
The REST endpoint paths (`http://localhost:8080/...`) shown are quite common, but vary with the server implementation used. See the notes at the end of this document.

MP Config::

The class `ConfigResource` publishes three REST endpoints for GET requests:

* `http://localhost:8080/config/java-version`: Return the Java version (system property value)
* `http://localhost:8080/config/home`: Return the use home directory path (from an environment variable)
* `http://localhost:8080/config/answer`: Return a value from `META-INF/microprofile-config.properties`
* `http://localhost:8080/config/profile`: Return two values changing with the configuration profile (set by the property `mp.config.profile`)
* `http://localhost:8080/config/expression`: Return a value from a property expession using several other properties

MP Health::

The package `de.gedoplan.showcase.health` contains a liveness and a readiness check. Both are simulated and get their status from a simple boolean config property.

MP Health offers the REST endpoints `http://localhost:8080/health/live` and `http://localhost:8080/health/ready`.

MP Metrics::

The class `TimedResource` contains a REST endpoint returning `hello` while providing call count and time statistics for calls of `http://localhost:8080/timed`. In order to generate some resonable demo data, the calls are randomly delayed. Execute a few calls before requesting metrics.

Another class - `de.gedoplan.showcase.metrics.CustomMetricsService` - demonstrates how to supply arbitrary application data as metrics.

MP Metrics offers the REST endpoints `http://localhost:8080/metrics/base`, `http://localhost:8080/metrics/vendor` and `http://localhost:8080/metrics/application` for scoped metrics and `http://localhost:8080/metrics` as overall aggregation.
You can switch from OpenMetrics format (a.k.a. Prometheus format) to JSON by using the header `accept: application/json`.
Times in OpenMetrics format are in seconds whereas times in JSON are in nanoseconds.

MP Rest Client::

`de.gedoplan.showcase.restclient.restcountries.eu.CountryApi` defines part of the public API of `http://restcountries.eu`, a demo service supplying various country data. Unfortunately the service has been replaced recently by `http://countrylayer.com/` requiring a (free) registration. Therefore this project supplies a mock service `RestCountriesEuMockResource`. `META-INF/microprofile-config.properties` contains the local mock uri.

`de.gedoplan.showcase.restclient` demonstrates access to the (mocked) external service with these endpoints:

* `http://localhost:8080/restclient`: using an injected MP REST proxy,
* `http://localhost:8080/restclient/api`: using the MP REST proxy via api,
* `http://localhost:8080/restclient/classic`: using the REST client api from Jakarta RESTful Webservice.

== Standard JEE server deployment

The WAR file can be deployed in any Jakarta EE 8 & MicroProfile 4 server, e. g. WildFly 24.

== WildFly Bootable JAR

The project defines the maven profile `wildfly-bootable-jar`. If it's activated for building (i. e. `mvn -Pwildfly-bootable-jar`) an additional JAR file is built: `target/microprofile-demo-bootable.jar` (*). It is a hollow JAR containing a WildFly server customized to just the extension needed (`jaxrs`, `cdi`, `microprofile-platform`). The application can be started by

`java -jar target/wildfly-bootable.jar --deployment=target/microprofile-demo.war`

The WildFly JAR plugin used for building the hollow JAR can also start the application in development mode:

`mvn -Pwildfly-bootable-jar wildfly-jar:dev-watch`

In this mode the server watches the program sources and hot reloads the application if something changes.

== Payara Micro

If you enable the maven profile `payara-micro` (i. e. `mvn -Ppayara-micro`), Payara Micro is downloaded into `target/payara-micro.jar`. It's a Jakarta EE Web Profile server including some extensions. The application can be started by

`java -jar target/payara-micro.jar target/microprofile-demo.war`

== Quarkus

The Quarkus build can be run with `mvn -Pquarkus`. It results in a directory `target\quarkus-app` containing the runner JAR `quarkus-run.jar` and subdirectories for application and runtime infrastructure. The application can be started by

`java -jar target/quarkus-app/quarkus-run.jar`

The Quarkus plugin used for building can also start the application in development mode:

`mvn -Pquarkus quarkus:dev`

In this mode the runtime watches the program sources and hot reloads the application if something changes.

It should be noted, that the project setup for quarkus in `pom.xml` is more complicated than it would be in normal projects: We wanted to have exactly the same source for both classical JEE environments and quarkus. This made it necessary to swich the project packaging from `war` for JEE to `jar` for Quarkus with the help of the maven property `packaging.type`, which can be done only, if the Quarkus plugin is configured with `quarkus.bootstrap.effective-model-builder` as `true`. The drawback of using the effective POM is a slower build, so you would not enable this option in normal projects.

== Notes

* WildFly:
** uses port `9990` instead of `8080` for MicroProfile endpoints (e. g. `http://localhost:9990/health/live`).

* Quarkus:
** uses the context `q` as default for MicroProfile endpoints (e. g. `http://localhost:8080/q/health/live`). 
This additional context has been disabled in `application.properties` to match the endpoints of the other environments.
** has its own configuration profile feature: Property `quarkus.profile` is kind of a predecessor of `mp.config.profile`. Both properties are used when evaluating profiled configuration values (e.g. `%dev.database)`, but are set independently. This will have to be aligned in the future somehow.
