FROM open-liberty:19.0.0.9-javaee8
ADD --chown=1001:0 src/main/openliberty/server.xml /config/
ADD --chown=1001:0 src/main/openliberty/h2.jar /opt/ol/wlp/usr/shared/resources/h2/
ADD --chown=1001:0 maven/* /config/dropins/
